# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "centos6.5"

  # Fixes changes from https://github.com/mitchellh/vagrant/pull/4707
  config.ssh.insert_key = false

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.

  # CentOS 6.5 x86_64
  config.vm.box_url = "https://atlas.hashicorp.com/puppetlabs/boxes/centos-6.6-64-puppet"

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", 3072] # RAM allocated to each VM
  end

  config.vm.provision :shell, :path => "bootstrap.sh"

  config.vm.define :master do |master|
    # uncomment the line below to set up the ambari dev environment
    # master.vm.provision :shell, :path => "dev-bootstrap.sh"
    master.vm.hostname = "master.ambari.keedio.org"
    master.vm.network :private_network, ip: "192.168.65.101"
  end

  config.vm.define :ambari1 do |ambari1|
    ambari1.vm.hostname = "ambari1.ambari.keedio.org"
    ambari1.vm.network :private_network, ip: "192.168.65.102"
  end

  config.vm.define :ambari2 do |ambari2|
    ambari2.vm.hostname = "ambari2.ambari.keedio.org"
    ambari2.vm.network :private_network, ip: "192.168.65.103"
  end

  config.vm.define :ambari3 do |ambari3|
    ambari3.vm.hostname = "ambari3.ambari.keedio.org"
    ambari3.vm.network :private_network, ip: "192.168.65.104"
  end

  config.vm.define :ambari4 do |ambari4|
    ambari4.vm.hostname = "ambari4.ambari.keedio.org"
    ambari4.vm.network :private_network, ip: "192.168.65.105"
  end

  config.vm.define :ambari5 do |ambari5|
    ambari5.vm.hostname = "ambari5.ambari.keedio.org"
    ambari5.vm.network :private_network, ip: "192.168.65.106"
  end

  config.vm.define :ambari6 do |ambari6|
    ambari6.vm.hostname = "ambari6.ambari.keedio.org"
    ambari6.vm.network :private_network, ip: "192.168.65.107"
  end

  config.vm.define :ambari7 do |ambari7|
    ambari7.vm.hostname = "ambari7.ambari.keedio.org"
    ambari7.vm.network :private_network, ip: "192.168.65.108"
  end

  config.vm.define :ambari8 do |ambari8|
    ambari8.vm.hostname = "ambari8.ambari.keedio.org"
    ambari8.vm.network :private_network, ip: "192.168.65.109"
  end

  config.vm.define :ambari9 do |ambari9|
    ambari9.vm.hostname = "ambari9.ambari.keedio.org"
    ambari9.vm.network :private_network, ip: "192.168.65.110"
  end













  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # config.vm.network :forwarded_port, guest: 80, host: 8080

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network :private_network, ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network :public_network

  # If true, then any SSH connections made will enable agent forwarding.
  # Default value: false
  # config.ssh.forward_agent = true

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider :virtualbox do |vb|
  #   # Don't boot with headless mode
  #   vb.gui = true
  #
  #   # Use VBoxManage to customize the VM. For example to change memory:
  #   vb.customize ["modifyvm", :id, "--memory", "1024"]
  # end
  #
  # View the documentation for the provider you're using for more
  # information on available options.

  # Enable provisioning with Puppet stand alone.  Puppet manifests
  # are contained in a directory path relative to this Vagrantfile.
  # You will need to create the manifests directory and a manifest in
  # the file precise32.pp in the manifests_path directory.
  #
  # An example Puppet manifest to provision the message of the day:
  #
  # # group { "puppet":
  # #   ensure => "present",
  # # }
  # #
  # # File { owner => 0, group => 0, mode => 0644 }
  # #
  # # file { '/etc/motd':
  # #   content => "Welcome to your Vagrant-built virtual machine!
  # #               Managed by Puppet.\n"
  # # }
  #
   config.vm.provision :puppet, 
     :options => ["--fileserverconfig=/vagrant/fileserver.conf","--pluginsync"],
     :facter => { "fqdn" => "vagrant.vagrantup.com" } do |puppet| 
     puppet.manifests_path = "manifests"
     puppet.module_path = "manifests/modules"
     puppet.manifest_file  = "init.pp"
   end

  # Enable provisioning with chef solo, specifying a cookbooks path, roles
  # path, and data_bags path (all relative to this Vagrantfile), and adding
  # some recipes and/or roles.
  #
  # config.vm.provision :chef_solo do |chef|
  #   chef.cookbooks_path = "../my-recipes/cookbooks"
  #   chef.roles_path = "../my-recipes/roles"
  #   chef.data_bags_path = "../my-recipes/data_bags"
  #   chef.add_recipe "mysql"
  #   chef.add_role "web"
  #
  #   # You may also specify custom JSON attributes:
  #   chef.json = { :mysql_password => "foo" }
  # end

  # Enable provisioning with chef server, specifying the chef server URL,
  # and the path to the validation key (relative to this Vagrantfile).
  #
  # The Opscode Platform uses HTTPS. Substitute your organization for
  # ORGNAME in the URL and validation key.
  #
  # If you have your own Chef Server, use the appropriate URL, which may be
  # HTTP instead of HTTPS depending on your configuration. Also change the
  # validation key to validation.pem.
  #
  # config.vm.provision :chef_client do |chef|
  #   chef.chef_server_url = "https://api.opscode.com/organizations/ORGNAME"
  #   chef.validation_key_path = "ORGNAME-validator.pem"
  # end
  #
  # If you're using the Opscode platform, your validator client is
  # ORGNAME-validator, replacing ORGNAME with your organization name.
  #
  # If you have your own Chef Server, the default validation client name is
  # chef-validator, unless you changed the configuration.
  #
  #   chef.validation_client_name = "ORGNAME-validator"
end
