name    'rtyler-groovy'
version '1.0.3'
source 'https://github.com/jenkins-infra/puppet-groovy'
author 'R. Tyler Croy'
license 'Apache License, Version 2.0'
summary 'Puppet module for installing Groovy from the official distribution.'
description 'This module installs Groovy from the offical project site.'
project_page 'https://github.com/jenkins-infra/puppet-groovy'

dependency 'nanliu/staging', '>= 0.4.0'
dependency 'puppetlabs/stdlib', '>= 3.0.0'
